name: Anchore

on: [push, pull_request]

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.18.0
        with:
          # scan entire repo
          path: .
          # JSON format (SPDX)
          format: spdx-json
          # artifact name
          artifact-name: sbom.spdx.json
          upload-artifact: true

  scan-sbom:
    name: SCA Scan (Grype)
    runs-on: ubuntu-latest
    needs: generate-sbom
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom.spdx.json
          path: .

      - name: Scan SBOM with Grype
        uses: anchore/scan-action@v6.1.0
        id: sbom_scan
        with:
          # point to the generated SBOM
          sbom: ./sbom.spdx.json
          # JSON output format
          output-format: json
          # write the report to this file
          output-file: sca-report.json
          # do not fail the build if vulnerabilities are found
          fail-build: false

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: sca-report.json
          path: sca-report.json
