name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Actualización a la versión más reciente de Hadolint
      - name: Set up Dockerfile linter (Hadolint)
        uses: hadolint/hadolint-action@v2.5.0  # Usamos una versión estable más reciente
        with:
          dockerfile: ./Dockerfile

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint code with Pylint
        run: |
          pylint **/*.py --disable=C,R0801,import-error --fail-under=7

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run unit tests
        run: |
          pytest unit_tests --maxfail=1 --disable-warnings -q

      - name: Run integration tests
        run: |
          pytest integration_tests --maxfail=1 --disable-warnings -q

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Bandit
        run: |
          python -m pip install bandit

      - name: Run Bandit SAST scan
        run: |
          bandit -r . --exclude unit_tests,integration_tests
